from __future__ import annotations
from abc import ABC, abstractmethod
from services.nubra_client.broker_types import BrokerOrder, BrokerOrderResult

# Implement this interface to add a new broker; register it in BrokerRegistry.
class BrokerClient(ABC):
    @abstractmethod
    def place_order(self, order: BrokerOrder) -> BrokerOrderResult: ...
    @abstractmethod
    def cancel_order(self, broker_order_id: str) -> bool: ...
    @abstractmethod
    def modify_order(self, broker_order_id: str, **changes) -> BrokerOrderResult: ...
    @abstractmethod
    def get_order_status(self, broker_order_id: str) -> BrokerOrderResult | None: ...
    @abstractmethod
    def get_positions(self) -> list[dict]: ...
    @abstractmethod
    def get_funds(self) -> dict: ...
